am=input("Assigment Mark: ")
tm=input("Test Mark: ")
em=input("Exam Mark: ")
ac=input("Assignment Contribution: ")
tc=input("Test Contribution: ")
ec=input("Exam Contribution: ")
assigment=int(input("assigment marks"))
test=int(input("test marks"))
exam=int(input("exam mark"))
Assigment=int(input("assigment contribution"))
Test=int(input("test contribution"))
Exam=int(input("exam contribution"))
FG=int(input("Final Grade"))
print("----- Student Result -----")
print(am,assigment)
print(tm,test)
print(em,exam)
print( )
print(ac,Assigment)
print(tc, Test)
print(ec, Exam)
print()
print(FG)